
on:
  push:
    branches:
      - develop_cicd


env:
  NODE_VERSION: '14.17.4'               # set this to the node version to use

jobs:
  build:
    name: Build
    runs-on: windows-2019
    
    strategy:
      matrix:
        node-version: [12.14, 14.17.4, 15.14.0]
        
    environment: production
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        # Build and start frond end
        npm install
        npm run build
  test:
    name: Test
    runs-on: windows-2019
    
    strategy:
      matrix:
        node-version: [12.14, 14.17.4, 15.14.0]
        
    environment: production
    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: ng test
      run: |
        # Run unit tests
        npm install
        npm run build
        npm test
